### ISSUE TITLE
New Varibles in ScanPolicy for Linux

### ISSUE THREAD

**Issue by 5T33Z0** [i3p9/oc-scanpolicy#1]
In OC 073 has new bits for Linux which changes the overall ScanPolicy Generation. So an update would be cool

00001000 OC_SCAN_ALLOW_FS_LINUX_ROOT 
00002000 OC_SCAN_ALLOW_FS_LINUX_DATA
00004000 OC_SCAN_ALLOW_FS_XBOOTLDR

**Comment by i3p9** [comment]
@5T33Z0  Thanks for the heads up, shouldn't be too hard to fix. I'll push a change in a sec!

Edit: Should be fixed. Please let me know if there's anything wrong. Thanks!

**Comment by perez987** [comment]
Thanks!!!
